-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity clip24 is
port (
    ap_ready : OUT STD_LOGIC;
    v_V : IN STD_LOGIC_VECTOR (25 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of clip24 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv26_3800000 : STD_LOGIC_VECTOR (25 downto 0) := "11100000000000000000000000";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_24_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln895_fu_34_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_fu_40_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln895_fu_58_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln895_fu_50_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln68_fu_46_p1 : STD_LOGIC_VECTOR (23 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        select_ln895_fu_50_p3 when (or_ln895_fu_58_p2(0) = '1') else 
        trunc_ln68_fu_46_p1;
    icmp_ln887_fu_40_p2 <= "1" when (signed(v_V) < signed(ap_const_lv26_3800000)) else "0";
    icmp_ln895_fu_34_p2 <= "1" when (signed(tmp_fu_24_p4) > signed(ap_const_lv3_0)) else "0";
    or_ln895_fu_58_p2 <= (icmp_ln895_fu_34_p2 or icmp_ln887_fu_40_p2);
    select_ln895_fu_50_p3 <= 
        ap_const_lv24_7FFFFF when (icmp_ln895_fu_34_p2(0) = '1') else 
        ap_const_lv24_800000;
    tmp_fu_24_p4 <= v_V(25 downto 23);
    trunc_ln68_fu_46_p1 <= v_V(24 - 1 downto 0);
end behav;
