-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fx_gain is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_TVALID : IN STD_LOGIC;
    m_axis_TREADY : IN STD_LOGIC;
    s_axis_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_TREADY : OUT STD_LOGIC;
    s_axis_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_TVALID : OUT STD_LOGIC;
    m_axis_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of fx_gain is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fx_gain,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=8.185000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=256,HLS_SYN_LUT=454,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv16_5A82 : STD_LOGIC_VECTOR (15 downto 0) := "0101101010000010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal tmp_nbreadreq_fu_92_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal m_axis_V_data_V_1_ack_in : STD_LOGIC;
    signal tmp_reg_236 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_io : BOOLEAN;
    signal m_axis_V_data_V_1_ack_out : STD_LOGIC;
    signal m_axis_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_V_keep_V_1_ack_out : STD_LOGIC;
    signal m_axis_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_V_strb_V_1_ack_out : STD_LOGIC;
    signal m_axis_V_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_V_user_V_1_ack_out : STD_LOGIC;
    signal m_axis_V_user_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_V_last_V_1_ack_out : STD_LOGIC;
    signal m_axis_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_V_id_V_1_ack_out : STD_LOGIC;
    signal m_axis_V_id_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_V_dest_V_1_ack_out : STD_LOGIC;
    signal m_axis_V_dest_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal tmp_reg_236_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal m_axis_V_data_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_V_data_V_1_vld_in : STD_LOGIC;
    signal m_axis_V_data_V_1_vld_out : STD_LOGIC;
    signal m_axis_V_data_V_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_V_data_V_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_V_data_V_1_sel : STD_LOGIC;
    signal m_axis_V_data_V_1_load_A : STD_LOGIC;
    signal m_axis_V_data_V_1_load_B : STD_LOGIC;
    signal m_axis_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_V_keep_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_V_keep_V_1_vld_in : STD_LOGIC;
    signal m_axis_V_keep_V_1_vld_out : STD_LOGIC;
    signal m_axis_V_keep_V_1_ack_in : STD_LOGIC;
    signal m_axis_V_keep_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_V_keep_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_V_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_V_keep_V_1_sel : STD_LOGIC;
    signal m_axis_V_keep_V_1_load_A : STD_LOGIC;
    signal m_axis_V_keep_V_1_load_B : STD_LOGIC;
    signal m_axis_V_keep_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_V_strb_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_V_strb_V_1_vld_in : STD_LOGIC;
    signal m_axis_V_strb_V_1_vld_out : STD_LOGIC;
    signal m_axis_V_strb_V_1_ack_in : STD_LOGIC;
    signal m_axis_V_strb_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_V_strb_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_V_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_V_strb_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_V_strb_V_1_sel : STD_LOGIC;
    signal m_axis_V_strb_V_1_load_A : STD_LOGIC;
    signal m_axis_V_strb_V_1_load_B : STD_LOGIC;
    signal m_axis_V_strb_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_V_user_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_user_V_1_vld_in : STD_LOGIC;
    signal m_axis_V_user_V_1_vld_out : STD_LOGIC;
    signal m_axis_V_user_V_1_ack_in : STD_LOGIC;
    signal m_axis_V_user_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_user_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_user_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_V_user_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_V_user_V_1_sel : STD_LOGIC;
    signal m_axis_V_user_V_1_load_A : STD_LOGIC;
    signal m_axis_V_user_V_1_load_B : STD_LOGIC;
    signal m_axis_V_user_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_last_V_1_vld_in : STD_LOGIC;
    signal m_axis_V_last_V_1_vld_out : STD_LOGIC;
    signal m_axis_V_last_V_1_ack_in : STD_LOGIC;
    signal m_axis_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_V_last_V_1_sel : STD_LOGIC;
    signal m_axis_V_last_V_1_load_A : STD_LOGIC;
    signal m_axis_V_last_V_1_load_B : STD_LOGIC;
    signal m_axis_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_V_id_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_id_V_1_vld_in : STD_LOGIC;
    signal m_axis_V_id_V_1_vld_out : STD_LOGIC;
    signal m_axis_V_id_V_1_ack_in : STD_LOGIC;
    signal m_axis_V_id_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_id_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_id_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_V_id_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_V_id_V_1_sel : STD_LOGIC;
    signal m_axis_V_id_V_1_load_A : STD_LOGIC;
    signal m_axis_V_id_V_1_load_B : STD_LOGIC;
    signal m_axis_V_id_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_V_dest_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_dest_V_1_vld_in : STD_LOGIC;
    signal m_axis_V_dest_V_1_vld_out : STD_LOGIC;
    signal m_axis_V_dest_V_1_ack_in : STD_LOGIC;
    signal m_axis_V_dest_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_dest_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_V_dest_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_V_dest_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_V_dest_V_1_sel : STD_LOGIC;
    signal m_axis_V_dest_V_1_load_A : STD_LOGIC;
    signal m_axis_V_dest_V_1_load_B : STD_LOGIC;
    signal m_axis_V_dest_V_1_state_cmp_full : STD_LOGIC;
    signal gain_q2_14_V : STD_LOGIC_VECTOR (15 downto 0);
    signal use_reg_V : STD_LOGIC_VECTOR (0 downto 0);
    signal s_axis_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal m_axis_TDATA_blk_n : STD_LOGIC;
    signal tmp_data_V_1_reg_240 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_keep_V_reg_245 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_V_reg_250 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_user_V_reg_255 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_260 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_265 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_270 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_275 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Result_s_fu_217_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal y_V_clip24_fu_155_ap_ready : STD_LOGIC;
    signal y_V_clip24_fu_155_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal s_V_fu_188_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal G_V_fu_192_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal prod_V_fu_229_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component clip24 IS
    port (
        ap_ready : OUT STD_LOGIC;
        v_V : IN STD_LOGIC_VECTOR (25 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component fx_gain_mul_mul_16s_24s_40_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component fx_gain_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        gain_q2_14_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        use_reg_V : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    fx_gain_CTRL_s_axi_U : component fx_gain_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        gain_q2_14_V => gain_q2_14_V,
        use_reg_V => use_reg_V);

    y_V_clip24_fu_155 : component clip24
    port map (
        ap_ready => y_V_clip24_fu_155_ap_ready,
        v_V => trunc_ln_reg_275,
        ap_return => y_V_clip24_fu_155_ap_return);

    fx_gain_mul_mul_16s_24s_40_1_1_U2 : component fx_gain_mul_mul_16s_24s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 24,
        dout_WIDTH => 40)
    port map (
        din0 => G_V_fu_192_p3,
        din1 => s_V_fu_188_p1,
        dout => prod_V_fu_229_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_V_data_V_1_ack_out = ap_const_logic_1) and (m_axis_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        m_axis_V_data_V_1_sel_rd <= not(m_axis_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_V_data_V_1_ack_in = ap_const_logic_1) and (m_axis_V_data_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_V_data_V_1_sel_wr <= not(m_axis_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_V_data_V_1_state = ap_const_lv2_3) and (m_axis_V_data_V_1_vld_in = ap_const_logic_0) and (m_axis_V_data_V_1_ack_out = ap_const_logic_1)) or ((m_axis_V_data_V_1_state = ap_const_lv2_2) and (m_axis_V_data_V_1_vld_in = ap_const_logic_0)))) then 
                    m_axis_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_V_data_V_1_state = ap_const_lv2_1) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_data_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0) and (m_axis_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_data_V_1_state <= ap_const_lv2_1;
                elsif ((((m_axis_V_data_V_1_state = ap_const_lv2_1) and (m_axis_V_data_V_1_ack_out = ap_const_logic_1)) or (not(((m_axis_V_data_V_1_vld_in = ap_const_logic_0) and (m_axis_V_data_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_TREADY = ap_const_logic_0) and (m_axis_V_data_V_1_vld_in = ap_const_logic_1))) and (m_axis_V_data_V_1_state = ap_const_lv2_3)) or ((m_axis_V_data_V_1_state = ap_const_lv2_2) and (m_axis_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_dest_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_dest_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_V_dest_V_1_vld_out = ap_const_logic_1) and (m_axis_V_dest_V_1_ack_out = ap_const_logic_1))) then 
                                        m_axis_V_dest_V_1_sel_rd <= not(m_axis_V_dest_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_dest_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_dest_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_V_dest_V_1_ack_in = ap_const_logic_1) and (m_axis_V_dest_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_V_dest_V_1_sel_wr <= not(m_axis_V_dest_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_dest_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_dest_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_V_dest_V_1_state = ap_const_lv2_3) and (m_axis_V_dest_V_1_vld_in = ap_const_logic_0) and (m_axis_V_dest_V_1_ack_out = ap_const_logic_1)) or ((m_axis_V_dest_V_1_state = ap_const_lv2_2) and (m_axis_V_dest_V_1_vld_in = ap_const_logic_0)))) then 
                    m_axis_V_dest_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_V_dest_V_1_state = ap_const_lv2_1) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_dest_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0) and (m_axis_V_dest_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_dest_V_1_state <= ap_const_lv2_1;
                elsif ((((m_axis_V_dest_V_1_state = ap_const_lv2_1) and (m_axis_V_dest_V_1_ack_out = ap_const_logic_1)) or (not(((m_axis_V_dest_V_1_vld_in = ap_const_logic_0) and (m_axis_V_dest_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_TREADY = ap_const_logic_0) and (m_axis_V_dest_V_1_vld_in = ap_const_logic_1))) and (m_axis_V_dest_V_1_state = ap_const_lv2_3)) or ((m_axis_V_dest_V_1_state = ap_const_lv2_2) and (m_axis_V_dest_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_dest_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_V_dest_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_id_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_id_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_V_id_V_1_vld_out = ap_const_logic_1) and (m_axis_V_id_V_1_ack_out = ap_const_logic_1))) then 
                                        m_axis_V_id_V_1_sel_rd <= not(m_axis_V_id_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_id_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_id_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_V_id_V_1_ack_in = ap_const_logic_1) and (m_axis_V_id_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_V_id_V_1_sel_wr <= not(m_axis_V_id_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_id_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_id_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_V_id_V_1_state = ap_const_lv2_3) and (m_axis_V_id_V_1_vld_in = ap_const_logic_0) and (m_axis_V_id_V_1_ack_out = ap_const_logic_1)) or ((m_axis_V_id_V_1_state = ap_const_lv2_2) and (m_axis_V_id_V_1_vld_in = ap_const_logic_0)))) then 
                    m_axis_V_id_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_V_id_V_1_state = ap_const_lv2_1) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_id_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0) and (m_axis_V_id_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_id_V_1_state <= ap_const_lv2_1;
                elsif ((((m_axis_V_id_V_1_state = ap_const_lv2_1) and (m_axis_V_id_V_1_ack_out = ap_const_logic_1)) or (not(((m_axis_V_id_V_1_vld_in = ap_const_logic_0) and (m_axis_V_id_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_TREADY = ap_const_logic_0) and (m_axis_V_id_V_1_vld_in = ap_const_logic_1))) and (m_axis_V_id_V_1_state = ap_const_lv2_3)) or ((m_axis_V_id_V_1_state = ap_const_lv2_2) and (m_axis_V_id_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_id_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_V_id_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_V_keep_V_1_ack_out = ap_const_logic_1) and (m_axis_V_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        m_axis_V_keep_V_1_sel_rd <= not(m_axis_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_V_keep_V_1_ack_in = ap_const_logic_1) and (m_axis_V_keep_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_V_keep_V_1_sel_wr <= not(m_axis_V_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_V_keep_V_1_state = ap_const_lv2_3) and (m_axis_V_keep_V_1_vld_in = ap_const_logic_0) and (m_axis_V_keep_V_1_ack_out = ap_const_logic_1)) or ((m_axis_V_keep_V_1_state = ap_const_lv2_2) and (m_axis_V_keep_V_1_vld_in = ap_const_logic_0)))) then 
                    m_axis_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_V_keep_V_1_state = ap_const_lv2_1) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_keep_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0) and (m_axis_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_keep_V_1_state <= ap_const_lv2_1;
                elsif ((((m_axis_V_keep_V_1_state = ap_const_lv2_1) and (m_axis_V_keep_V_1_ack_out = ap_const_logic_1)) or (not(((m_axis_V_keep_V_1_vld_in = ap_const_logic_0) and (m_axis_V_keep_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_TREADY = ap_const_logic_0) and (m_axis_V_keep_V_1_vld_in = ap_const_logic_1))) and (m_axis_V_keep_V_1_state = ap_const_lv2_3)) or ((m_axis_V_keep_V_1_state = ap_const_lv2_2) and (m_axis_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_V_last_V_1_vld_out = ap_const_logic_1) and (m_axis_V_last_V_1_ack_out = ap_const_logic_1))) then 
                                        m_axis_V_last_V_1_sel_rd <= not(m_axis_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_V_last_V_1_ack_in = ap_const_logic_1) and (m_axis_V_last_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_V_last_V_1_sel_wr <= not(m_axis_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_V_last_V_1_state = ap_const_lv2_3) and (m_axis_V_last_V_1_vld_in = ap_const_logic_0) and (m_axis_V_last_V_1_ack_out = ap_const_logic_1)) or ((m_axis_V_last_V_1_state = ap_const_lv2_2) and (m_axis_V_last_V_1_vld_in = ap_const_logic_0)))) then 
                    m_axis_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_V_last_V_1_state = ap_const_lv2_1) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_last_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0) and (m_axis_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_last_V_1_state <= ap_const_lv2_1;
                elsif ((((m_axis_V_last_V_1_state = ap_const_lv2_1) and (m_axis_V_last_V_1_ack_out = ap_const_logic_1)) or (not(((m_axis_V_last_V_1_vld_in = ap_const_logic_0) and (m_axis_V_last_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_TREADY = ap_const_logic_0) and (m_axis_V_last_V_1_vld_in = ap_const_logic_1))) and (m_axis_V_last_V_1_state = ap_const_lv2_3)) or ((m_axis_V_last_V_1_state = ap_const_lv2_2) and (m_axis_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_V_strb_V_1_ack_out = ap_const_logic_1) and (m_axis_V_strb_V_1_vld_out = ap_const_logic_1))) then 
                                        m_axis_V_strb_V_1_sel_rd <= not(m_axis_V_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_strb_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_strb_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_V_strb_V_1_ack_in = ap_const_logic_1) and (m_axis_V_strb_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_V_strb_V_1_sel_wr <= not(m_axis_V_strb_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_V_strb_V_1_state = ap_const_lv2_3) and (m_axis_V_strb_V_1_vld_in = ap_const_logic_0) and (m_axis_V_strb_V_1_ack_out = ap_const_logic_1)) or ((m_axis_V_strb_V_1_state = ap_const_lv2_2) and (m_axis_V_strb_V_1_vld_in = ap_const_logic_0)))) then 
                    m_axis_V_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_V_strb_V_1_state = ap_const_lv2_1) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_strb_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0) and (m_axis_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_strb_V_1_state <= ap_const_lv2_1;
                elsif ((((m_axis_V_strb_V_1_state = ap_const_lv2_1) and (m_axis_V_strb_V_1_ack_out = ap_const_logic_1)) or (not(((m_axis_V_strb_V_1_vld_in = ap_const_logic_0) and (m_axis_V_strb_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_TREADY = ap_const_logic_0) and (m_axis_V_strb_V_1_vld_in = ap_const_logic_1))) and (m_axis_V_strb_V_1_state = ap_const_lv2_3)) or ((m_axis_V_strb_V_1_state = ap_const_lv2_2) and (m_axis_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_strb_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_V_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_user_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_user_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_V_user_V_1_ack_out = ap_const_logic_1) and (m_axis_V_user_V_1_vld_out = ap_const_logic_1))) then 
                                        m_axis_V_user_V_1_sel_rd <= not(m_axis_V_user_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_user_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_user_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_V_user_V_1_ack_in = ap_const_logic_1) and (m_axis_V_user_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_V_user_V_1_sel_wr <= not(m_axis_V_user_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_V_user_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_V_user_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_V_user_V_1_state = ap_const_lv2_3) and (m_axis_V_user_V_1_vld_in = ap_const_logic_0) and (m_axis_V_user_V_1_ack_out = ap_const_logic_1)) or ((m_axis_V_user_V_1_state = ap_const_lv2_2) and (m_axis_V_user_V_1_vld_in = ap_const_logic_0)))) then 
                    m_axis_V_user_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_V_user_V_1_state = ap_const_lv2_1) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_user_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0) and (m_axis_V_user_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_user_V_1_state <= ap_const_lv2_1;
                elsif ((((m_axis_V_user_V_1_state = ap_const_lv2_1) and (m_axis_V_user_V_1_ack_out = ap_const_logic_1)) or (not(((m_axis_V_user_V_1_vld_in = ap_const_logic_0) and (m_axis_V_user_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_TREADY = ap_const_logic_0) and (m_axis_V_user_V_1_vld_in = ap_const_logic_1))) and (m_axis_V_user_V_1_state = ap_const_lv2_3)) or ((m_axis_V_user_V_1_state = ap_const_lv2_2) and (m_axis_V_user_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_V_user_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_V_user_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_data_V_1_load_A = ap_const_logic_1)) then
                m_axis_V_data_V_1_payload_A <= p_Result_s_fu_217_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_data_V_1_load_B = ap_const_logic_1)) then
                m_axis_V_data_V_1_payload_B <= p_Result_s_fu_217_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_dest_V_1_load_A = ap_const_logic_1)) then
                m_axis_V_dest_V_1_payload_A <= tmp_dest_V_reg_270;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_dest_V_1_load_B = ap_const_logic_1)) then
                m_axis_V_dest_V_1_payload_B <= tmp_dest_V_reg_270;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_id_V_1_load_A = ap_const_logic_1)) then
                m_axis_V_id_V_1_payload_A <= tmp_id_V_reg_265;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_id_V_1_load_B = ap_const_logic_1)) then
                m_axis_V_id_V_1_payload_B <= tmp_id_V_reg_265;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_keep_V_1_load_A = ap_const_logic_1)) then
                m_axis_V_keep_V_1_payload_A <= tmp_keep_V_reg_245;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_keep_V_1_load_B = ap_const_logic_1)) then
                m_axis_V_keep_V_1_payload_B <= tmp_keep_V_reg_245;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_last_V_1_load_A = ap_const_logic_1)) then
                m_axis_V_last_V_1_payload_A <= tmp_last_V_reg_260;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_last_V_1_load_B = ap_const_logic_1)) then
                m_axis_V_last_V_1_payload_B <= tmp_last_V_reg_260;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_strb_V_1_load_A = ap_const_logic_1)) then
                m_axis_V_strb_V_1_payload_A <= tmp_strb_V_reg_250;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_strb_V_1_load_B = ap_const_logic_1)) then
                m_axis_V_strb_V_1_payload_B <= tmp_strb_V_reg_250;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_user_V_1_load_A = ap_const_logic_1)) then
                m_axis_V_user_V_1_payload_A <= tmp_user_V_reg_255;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_V_user_V_1_load_B = ap_const_logic_1)) then
                m_axis_V_user_V_1_payload_B <= tmp_user_V_reg_255;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_92_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_data_V_1_reg_240 <= s_axis_TDATA;
                tmp_dest_V_reg_270 <= s_axis_TDEST;
                tmp_id_V_reg_265 <= s_axis_TID;
                tmp_keep_V_reg_245 <= s_axis_TKEEP;
                tmp_last_V_reg_260 <= s_axis_TLAST;
                tmp_strb_V_reg_250 <= s_axis_TSTRB;
                tmp_user_V_reg_255 <= s_axis_TUSER;
                trunc_ln_reg_275 <= prod_V_fu_229_p2(39 downto 14);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_236 <= tmp_nbreadreq_fu_92_p9;
                tmp_reg_236_pp0_iter1_reg <= tmp_reg_236;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    G_V_fu_192_p3 <= 
        gain_q2_14_V when (use_reg_V(0) = '1') else 
        ap_const_lv16_5A82;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter2, s_axis_TVALID, tmp_nbreadreq_fu_92_p9, m_axis_TREADY, m_axis_V_data_V_1_state, m_axis_V_keep_V_1_state, m_axis_V_strb_V_1_state, m_axis_V_user_V_1_state, m_axis_V_last_V_1_state, m_axis_V_id_V_1_state, m_axis_V_dest_V_1_state)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_92_p9 = ap_const_lv1_1) and (s_axis_TVALID = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((m_axis_V_user_V_1_state = ap_const_lv2_1) or (m_axis_V_strb_V_1_state = ap_const_lv2_1) or (m_axis_V_keep_V_1_state = ap_const_lv2_1) or (m_axis_V_dest_V_1_state = ap_const_lv2_1) or (m_axis_V_id_V_1_state = ap_const_lv2_1) or (m_axis_V_last_V_1_state = ap_const_lv2_1) or (m_axis_V_data_V_1_state = ap_const_lv2_1) or ((m_axis_V_user_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_strb_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_keep_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_data_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_dest_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_id_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_last_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, s_axis_TVALID, tmp_nbreadreq_fu_92_p9, m_axis_TREADY, ap_block_state2_io, m_axis_V_data_V_1_state, m_axis_V_keep_V_1_state, m_axis_V_strb_V_1_state, m_axis_V_user_V_1_state, m_axis_V_last_V_1_state, m_axis_V_id_V_1_state, m_axis_V_dest_V_1_state, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_92_p9 = ap_const_lv1_1) and (s_axis_TVALID = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((m_axis_V_user_V_1_state = ap_const_lv2_1) or (m_axis_V_strb_V_1_state = ap_const_lv2_1) or (m_axis_V_keep_V_1_state = ap_const_lv2_1) or (m_axis_V_dest_V_1_state = ap_const_lv2_1) or (m_axis_V_id_V_1_state = ap_const_lv2_1) or (m_axis_V_last_V_1_state = ap_const_lv2_1) or (m_axis_V_data_V_1_state = ap_const_lv2_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((m_axis_V_user_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_strb_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_keep_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_data_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_dest_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_id_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_last_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, s_axis_TVALID, tmp_nbreadreq_fu_92_p9, m_axis_TREADY, ap_block_state2_io, m_axis_V_data_V_1_state, m_axis_V_keep_V_1_state, m_axis_V_strb_V_1_state, m_axis_V_user_V_1_state, m_axis_V_last_V_1_state, m_axis_V_id_V_1_state, m_axis_V_dest_V_1_state, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_92_p9 = ap_const_lv1_1) and (s_axis_TVALID = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((m_axis_V_user_V_1_state = ap_const_lv2_1) or (m_axis_V_strb_V_1_state = ap_const_lv2_1) or (m_axis_V_keep_V_1_state = ap_const_lv2_1) or (m_axis_V_dest_V_1_state = ap_const_lv2_1) or (m_axis_V_id_V_1_state = ap_const_lv2_1) or (m_axis_V_last_V_1_state = ap_const_lv2_1) or (m_axis_V_data_V_1_state = ap_const_lv2_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((m_axis_V_user_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_strb_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_keep_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_data_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_dest_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_id_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_last_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, s_axis_TVALID, tmp_nbreadreq_fu_92_p9)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_92_p9 = ap_const_lv1_1) and (s_axis_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state2_io_assign_proc : process(m_axis_V_data_V_1_ack_in, tmp_reg_236)
    begin
                ap_block_state2_io <= ((tmp_reg_236 = ap_const_lv1_1) and (m_axis_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(m_axis_V_data_V_1_ack_in, tmp_reg_236_pp0_iter1_reg)
    begin
                ap_block_state3_io <= ((tmp_reg_236_pp0_iter1_reg = ap_const_lv1_1) and (m_axis_V_data_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(m_axis_TREADY, m_axis_V_data_V_1_state, m_axis_V_keep_V_1_state, m_axis_V_strb_V_1_state, m_axis_V_user_V_1_state, m_axis_V_last_V_1_state, m_axis_V_id_V_1_state, m_axis_V_dest_V_1_state)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((m_axis_V_user_V_1_state = ap_const_lv2_1) or (m_axis_V_strb_V_1_state = ap_const_lv2_1) or (m_axis_V_keep_V_1_state = ap_const_lv2_1) or (m_axis_V_dest_V_1_state = ap_const_lv2_1) or (m_axis_V_id_V_1_state = ap_const_lv2_1) or (m_axis_V_last_V_1_state = ap_const_lv2_1) or (m_axis_V_data_V_1_state = ap_const_lv2_1) or ((m_axis_V_user_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_strb_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_keep_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_data_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_dest_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_id_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)) or ((m_axis_V_last_V_1_state = ap_const_lv2_3) and (m_axis_TREADY = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    m_axis_TDATA <= m_axis_V_data_V_1_data_out;

    m_axis_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, tmp_reg_236, m_axis_V_data_V_1_state, tmp_reg_236_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_reg_236_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            m_axis_TDATA_blk_n <= m_axis_V_data_V_1_state(1);
        else 
            m_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_TDEST <= m_axis_V_dest_V_1_data_out;
    m_axis_TID <= m_axis_V_id_V_1_data_out;
    m_axis_TKEEP <= m_axis_V_keep_V_1_data_out;
    m_axis_TLAST <= m_axis_V_last_V_1_data_out;
    m_axis_TSTRB <= m_axis_V_strb_V_1_data_out;
    m_axis_TUSER <= m_axis_V_user_V_1_data_out;
    m_axis_TVALID <= m_axis_V_dest_V_1_state(0);
    m_axis_V_data_V_1_ack_in <= m_axis_V_data_V_1_state(1);
    m_axis_V_data_V_1_ack_out <= m_axis_TREADY;

    m_axis_V_data_V_1_data_out_assign_proc : process(m_axis_V_data_V_1_payload_A, m_axis_V_data_V_1_payload_B, m_axis_V_data_V_1_sel)
    begin
        if ((m_axis_V_data_V_1_sel = ap_const_logic_1)) then 
            m_axis_V_data_V_1_data_out <= m_axis_V_data_V_1_payload_B;
        else 
            m_axis_V_data_V_1_data_out <= m_axis_V_data_V_1_payload_A;
        end if; 
    end process;

    m_axis_V_data_V_1_load_A <= (m_axis_V_data_V_1_state_cmp_full and not(m_axis_V_data_V_1_sel_wr));
    m_axis_V_data_V_1_load_B <= (m_axis_V_data_V_1_state_cmp_full and m_axis_V_data_V_1_sel_wr);
    m_axis_V_data_V_1_sel <= m_axis_V_data_V_1_sel_rd;
    m_axis_V_data_V_1_state_cmp_full <= '0' when (m_axis_V_data_V_1_state = ap_const_lv2_1) else '1';

    m_axis_V_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_236, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_V_data_V_1_vld_out <= m_axis_V_data_V_1_state(0);
    m_axis_V_dest_V_1_ack_in <= m_axis_V_dest_V_1_state(1);
    m_axis_V_dest_V_1_ack_out <= m_axis_TREADY;

    m_axis_V_dest_V_1_data_out_assign_proc : process(m_axis_V_dest_V_1_payload_A, m_axis_V_dest_V_1_payload_B, m_axis_V_dest_V_1_sel)
    begin
        if ((m_axis_V_dest_V_1_sel = ap_const_logic_1)) then 
            m_axis_V_dest_V_1_data_out <= m_axis_V_dest_V_1_payload_B;
        else 
            m_axis_V_dest_V_1_data_out <= m_axis_V_dest_V_1_payload_A;
        end if; 
    end process;

    m_axis_V_dest_V_1_load_A <= (m_axis_V_dest_V_1_state_cmp_full and not(m_axis_V_dest_V_1_sel_wr));
    m_axis_V_dest_V_1_load_B <= (m_axis_V_dest_V_1_state_cmp_full and m_axis_V_dest_V_1_sel_wr);
    m_axis_V_dest_V_1_sel <= m_axis_V_dest_V_1_sel_rd;
    m_axis_V_dest_V_1_state_cmp_full <= '0' when (m_axis_V_dest_V_1_state = ap_const_lv2_1) else '1';

    m_axis_V_dest_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_236, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_V_dest_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_V_dest_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_V_dest_V_1_vld_out <= m_axis_V_dest_V_1_state(0);
    m_axis_V_id_V_1_ack_in <= m_axis_V_id_V_1_state(1);
    m_axis_V_id_V_1_ack_out <= m_axis_TREADY;

    m_axis_V_id_V_1_data_out_assign_proc : process(m_axis_V_id_V_1_payload_A, m_axis_V_id_V_1_payload_B, m_axis_V_id_V_1_sel)
    begin
        if ((m_axis_V_id_V_1_sel = ap_const_logic_1)) then 
            m_axis_V_id_V_1_data_out <= m_axis_V_id_V_1_payload_B;
        else 
            m_axis_V_id_V_1_data_out <= m_axis_V_id_V_1_payload_A;
        end if; 
    end process;

    m_axis_V_id_V_1_load_A <= (m_axis_V_id_V_1_state_cmp_full and not(m_axis_V_id_V_1_sel_wr));
    m_axis_V_id_V_1_load_B <= (m_axis_V_id_V_1_state_cmp_full and m_axis_V_id_V_1_sel_wr);
    m_axis_V_id_V_1_sel <= m_axis_V_id_V_1_sel_rd;
    m_axis_V_id_V_1_state_cmp_full <= '0' when (m_axis_V_id_V_1_state = ap_const_lv2_1) else '1';

    m_axis_V_id_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_236, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_V_id_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_V_id_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_V_id_V_1_vld_out <= m_axis_V_id_V_1_state(0);
    m_axis_V_keep_V_1_ack_in <= m_axis_V_keep_V_1_state(1);
    m_axis_V_keep_V_1_ack_out <= m_axis_TREADY;

    m_axis_V_keep_V_1_data_out_assign_proc : process(m_axis_V_keep_V_1_payload_A, m_axis_V_keep_V_1_payload_B, m_axis_V_keep_V_1_sel)
    begin
        if ((m_axis_V_keep_V_1_sel = ap_const_logic_1)) then 
            m_axis_V_keep_V_1_data_out <= m_axis_V_keep_V_1_payload_B;
        else 
            m_axis_V_keep_V_1_data_out <= m_axis_V_keep_V_1_payload_A;
        end if; 
    end process;

    m_axis_V_keep_V_1_load_A <= (m_axis_V_keep_V_1_state_cmp_full and not(m_axis_V_keep_V_1_sel_wr));
    m_axis_V_keep_V_1_load_B <= (m_axis_V_keep_V_1_state_cmp_full and m_axis_V_keep_V_1_sel_wr);
    m_axis_V_keep_V_1_sel <= m_axis_V_keep_V_1_sel_rd;
    m_axis_V_keep_V_1_state_cmp_full <= '0' when (m_axis_V_keep_V_1_state = ap_const_lv2_1) else '1';

    m_axis_V_keep_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_236, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_V_keep_V_1_vld_out <= m_axis_V_keep_V_1_state(0);
    m_axis_V_last_V_1_ack_in <= m_axis_V_last_V_1_state(1);
    m_axis_V_last_V_1_ack_out <= m_axis_TREADY;

    m_axis_V_last_V_1_data_out_assign_proc : process(m_axis_V_last_V_1_payload_A, m_axis_V_last_V_1_payload_B, m_axis_V_last_V_1_sel)
    begin
        if ((m_axis_V_last_V_1_sel = ap_const_logic_1)) then 
            m_axis_V_last_V_1_data_out <= m_axis_V_last_V_1_payload_B;
        else 
            m_axis_V_last_V_1_data_out <= m_axis_V_last_V_1_payload_A;
        end if; 
    end process;

    m_axis_V_last_V_1_load_A <= (m_axis_V_last_V_1_state_cmp_full and not(m_axis_V_last_V_1_sel_wr));
    m_axis_V_last_V_1_load_B <= (m_axis_V_last_V_1_state_cmp_full and m_axis_V_last_V_1_sel_wr);
    m_axis_V_last_V_1_sel <= m_axis_V_last_V_1_sel_rd;
    m_axis_V_last_V_1_state_cmp_full <= '0' when (m_axis_V_last_V_1_state = ap_const_lv2_1) else '1';

    m_axis_V_last_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_236, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_V_last_V_1_vld_out <= m_axis_V_last_V_1_state(0);
    m_axis_V_strb_V_1_ack_in <= m_axis_V_strb_V_1_state(1);
    m_axis_V_strb_V_1_ack_out <= m_axis_TREADY;

    m_axis_V_strb_V_1_data_out_assign_proc : process(m_axis_V_strb_V_1_payload_A, m_axis_V_strb_V_1_payload_B, m_axis_V_strb_V_1_sel)
    begin
        if ((m_axis_V_strb_V_1_sel = ap_const_logic_1)) then 
            m_axis_V_strb_V_1_data_out <= m_axis_V_strb_V_1_payload_B;
        else 
            m_axis_V_strb_V_1_data_out <= m_axis_V_strb_V_1_payload_A;
        end if; 
    end process;

    m_axis_V_strb_V_1_load_A <= (m_axis_V_strb_V_1_state_cmp_full and not(m_axis_V_strb_V_1_sel_wr));
    m_axis_V_strb_V_1_load_B <= (m_axis_V_strb_V_1_state_cmp_full and m_axis_V_strb_V_1_sel_wr);
    m_axis_V_strb_V_1_sel <= m_axis_V_strb_V_1_sel_rd;
    m_axis_V_strb_V_1_state_cmp_full <= '0' when (m_axis_V_strb_V_1_state = ap_const_lv2_1) else '1';

    m_axis_V_strb_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_236, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_V_strb_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_V_strb_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_V_strb_V_1_vld_out <= m_axis_V_strb_V_1_state(0);
    m_axis_V_user_V_1_ack_in <= m_axis_V_user_V_1_state(1);
    m_axis_V_user_V_1_ack_out <= m_axis_TREADY;

    m_axis_V_user_V_1_data_out_assign_proc : process(m_axis_V_user_V_1_payload_A, m_axis_V_user_V_1_payload_B, m_axis_V_user_V_1_sel)
    begin
        if ((m_axis_V_user_V_1_sel = ap_const_logic_1)) then 
            m_axis_V_user_V_1_data_out <= m_axis_V_user_V_1_payload_B;
        else 
            m_axis_V_user_V_1_data_out <= m_axis_V_user_V_1_payload_A;
        end if; 
    end process;

    m_axis_V_user_V_1_load_A <= (m_axis_V_user_V_1_state_cmp_full and not(m_axis_V_user_V_1_sel_wr));
    m_axis_V_user_V_1_load_B <= (m_axis_V_user_V_1_state_cmp_full and m_axis_V_user_V_1_sel_wr);
    m_axis_V_user_V_1_sel <= m_axis_V_user_V_1_sel_rd;
    m_axis_V_user_V_1_state_cmp_full <= '0' when (m_axis_V_user_V_1_state = ap_const_lv2_1) else '1';

    m_axis_V_user_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_236, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_236 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_V_user_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_V_user_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_V_user_V_1_vld_out <= m_axis_V_user_V_1_state(0);
    p_Result_s_fu_217_p5 <= (tmp_data_V_1_reg_240(31 downto 24) & y_V_clip24_fu_155_ap_return);
    s_V_fu_188_p1 <= s_axis_TDATA(24 - 1 downto 0);

    s_axis_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, s_axis_TVALID, tmp_nbreadreq_fu_92_p9, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_nbreadreq_fu_92_p9 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_TDATA_blk_n <= s_axis_TVALID;
        else 
            s_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_TREADY_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_92_p9, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_nbreadreq_fu_92_p9 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_axis_TREADY <= ap_const_logic_1;
        else 
            s_axis_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_92_p9 <= (0=>(s_axis_TVALID), others=>'-');
end behav;
