// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module clip24 (
        ap_ready,
        v_V,
        ap_return
);


output   ap_ready;
input  [25:0] v_V;
output  [23:0] ap_return;

wire   [2:0] tmp_fu_24_p4;
wire   [0:0] icmp_ln895_fu_34_p2;
wire   [0:0] icmp_ln887_fu_40_p2;
wire   [0:0] or_ln895_fu_58_p2;
wire   [23:0] select_ln895_fu_50_p3;
wire   [23:0] trunc_ln68_fu_46_p1;

assign ap_ready = 1'b1;

assign ap_return = ((or_ln895_fu_58_p2[0:0] === 1'b1) ? select_ln895_fu_50_p3 : trunc_ln68_fu_46_p1);

assign icmp_ln887_fu_40_p2 = (($signed(v_V) < $signed(26'd58720256)) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_34_p2 = (($signed(tmp_fu_24_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign or_ln895_fu_58_p2 = (icmp_ln895_fu_34_p2 | icmp_ln887_fu_40_p2);

assign select_ln895_fu_50_p3 = ((icmp_ln895_fu_34_p2[0:0] === 1'b1) ? 24'd8388607 : 24'd8388608);

assign tmp_fu_24_p4 = {{v_V[25:23]}};

assign trunc_ln68_fu_46_p1 = v_V[23:0];

endmodule //clip24
