// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fx_gain,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=8.185000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=256,HLS_SYN_LUT=454,HLS_VERSION=2019_1}" *)

module fx_gain (
        ap_clk,
        ap_rst_n,
        s_axis_TVALID,
        m_axis_TREADY,
        s_axis_TDATA,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TUSER,
        s_axis_TLAST,
        s_axis_TID,
        s_axis_TDEST,
        m_axis_TDATA,
        m_axis_TVALID,
        m_axis_TKEEP,
        m_axis_TSTRB,
        m_axis_TUSER,
        m_axis_TLAST,
        m_axis_TID,
        m_axis_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axis_TVALID;
input   m_axis_TREADY;
input  [31:0] s_axis_TDATA;
output   s_axis_TREADY;
input  [3:0] s_axis_TKEEP;
input  [3:0] s_axis_TSTRB;
input  [0:0] s_axis_TUSER;
input  [0:0] s_axis_TLAST;
input  [0:0] s_axis_TID;
input  [0:0] s_axis_TDEST;
output  [31:0] m_axis_TDATA;
output   m_axis_TVALID;
output  [3:0] m_axis_TKEEP;
output  [3:0] m_axis_TSTRB;
output  [0:0] m_axis_TUSER;
output  [0:0] m_axis_TLAST;
output  [0:0] m_axis_TID;
output  [0:0] m_axis_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

reg s_axis_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_ready;
wire   [0:0] tmp_nbreadreq_fu_92_p9;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    m_axis_V_data_V_1_ack_in;
reg   [0:0] tmp_reg_236;
reg    ap_block_state2_io;
wire    m_axis_V_data_V_1_ack_out;
reg   [1:0] m_axis_V_data_V_1_state;
wire    m_axis_V_keep_V_1_ack_out;
reg   [1:0] m_axis_V_keep_V_1_state;
wire    m_axis_V_strb_V_1_ack_out;
reg   [1:0] m_axis_V_strb_V_1_state;
wire    m_axis_V_user_V_1_ack_out;
reg   [1:0] m_axis_V_user_V_1_state;
wire    m_axis_V_last_V_1_ack_out;
reg   [1:0] m_axis_V_last_V_1_state;
wire    m_axis_V_id_V_1_ack_out;
reg   [1:0] m_axis_V_id_V_1_state;
wire    m_axis_V_dest_V_1_ack_out;
reg   [1:0] m_axis_V_dest_V_1_state;
reg    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] tmp_reg_236_pp0_iter1_reg;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] m_axis_V_data_V_1_data_out;
reg    m_axis_V_data_V_1_vld_in;
wire    m_axis_V_data_V_1_vld_out;
reg   [31:0] m_axis_V_data_V_1_payload_A;
reg   [31:0] m_axis_V_data_V_1_payload_B;
reg    m_axis_V_data_V_1_sel_rd;
reg    m_axis_V_data_V_1_sel_wr;
wire    m_axis_V_data_V_1_sel;
wire    m_axis_V_data_V_1_load_A;
wire    m_axis_V_data_V_1_load_B;
wire    m_axis_V_data_V_1_state_cmp_full;
reg   [3:0] m_axis_V_keep_V_1_data_out;
reg    m_axis_V_keep_V_1_vld_in;
wire    m_axis_V_keep_V_1_vld_out;
wire    m_axis_V_keep_V_1_ack_in;
reg   [3:0] m_axis_V_keep_V_1_payload_A;
reg   [3:0] m_axis_V_keep_V_1_payload_B;
reg    m_axis_V_keep_V_1_sel_rd;
reg    m_axis_V_keep_V_1_sel_wr;
wire    m_axis_V_keep_V_1_sel;
wire    m_axis_V_keep_V_1_load_A;
wire    m_axis_V_keep_V_1_load_B;
wire    m_axis_V_keep_V_1_state_cmp_full;
reg   [3:0] m_axis_V_strb_V_1_data_out;
reg    m_axis_V_strb_V_1_vld_in;
wire    m_axis_V_strb_V_1_vld_out;
wire    m_axis_V_strb_V_1_ack_in;
reg   [3:0] m_axis_V_strb_V_1_payload_A;
reg   [3:0] m_axis_V_strb_V_1_payload_B;
reg    m_axis_V_strb_V_1_sel_rd;
reg    m_axis_V_strb_V_1_sel_wr;
wire    m_axis_V_strb_V_1_sel;
wire    m_axis_V_strb_V_1_load_A;
wire    m_axis_V_strb_V_1_load_B;
wire    m_axis_V_strb_V_1_state_cmp_full;
reg   [0:0] m_axis_V_user_V_1_data_out;
reg    m_axis_V_user_V_1_vld_in;
wire    m_axis_V_user_V_1_vld_out;
wire    m_axis_V_user_V_1_ack_in;
reg   [0:0] m_axis_V_user_V_1_payload_A;
reg   [0:0] m_axis_V_user_V_1_payload_B;
reg    m_axis_V_user_V_1_sel_rd;
reg    m_axis_V_user_V_1_sel_wr;
wire    m_axis_V_user_V_1_sel;
wire    m_axis_V_user_V_1_load_A;
wire    m_axis_V_user_V_1_load_B;
wire    m_axis_V_user_V_1_state_cmp_full;
reg   [0:0] m_axis_V_last_V_1_data_out;
reg    m_axis_V_last_V_1_vld_in;
wire    m_axis_V_last_V_1_vld_out;
wire    m_axis_V_last_V_1_ack_in;
reg   [0:0] m_axis_V_last_V_1_payload_A;
reg   [0:0] m_axis_V_last_V_1_payload_B;
reg    m_axis_V_last_V_1_sel_rd;
reg    m_axis_V_last_V_1_sel_wr;
wire    m_axis_V_last_V_1_sel;
wire    m_axis_V_last_V_1_load_A;
wire    m_axis_V_last_V_1_load_B;
wire    m_axis_V_last_V_1_state_cmp_full;
reg   [0:0] m_axis_V_id_V_1_data_out;
reg    m_axis_V_id_V_1_vld_in;
wire    m_axis_V_id_V_1_vld_out;
wire    m_axis_V_id_V_1_ack_in;
reg   [0:0] m_axis_V_id_V_1_payload_A;
reg   [0:0] m_axis_V_id_V_1_payload_B;
reg    m_axis_V_id_V_1_sel_rd;
reg    m_axis_V_id_V_1_sel_wr;
wire    m_axis_V_id_V_1_sel;
wire    m_axis_V_id_V_1_load_A;
wire    m_axis_V_id_V_1_load_B;
wire    m_axis_V_id_V_1_state_cmp_full;
reg   [0:0] m_axis_V_dest_V_1_data_out;
reg    m_axis_V_dest_V_1_vld_in;
wire    m_axis_V_dest_V_1_vld_out;
wire    m_axis_V_dest_V_1_ack_in;
reg   [0:0] m_axis_V_dest_V_1_payload_A;
reg   [0:0] m_axis_V_dest_V_1_payload_B;
reg    m_axis_V_dest_V_1_sel_rd;
reg    m_axis_V_dest_V_1_sel_wr;
wire    m_axis_V_dest_V_1_sel;
wire    m_axis_V_dest_V_1_load_A;
wire    m_axis_V_dest_V_1_load_B;
wire    m_axis_V_dest_V_1_state_cmp_full;
wire   [15:0] gain_q2_14_V;
wire   [0:0] use_reg_V;
reg    s_axis_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    m_axis_TDATA_blk_n;
reg   [31:0] tmp_data_V_1_reg_240;
reg   [3:0] tmp_keep_V_reg_245;
reg   [3:0] tmp_strb_V_reg_250;
reg   [0:0] tmp_user_V_reg_255;
reg   [0:0] tmp_last_V_reg_260;
reg   [0:0] tmp_id_V_reg_265;
reg   [0:0] tmp_dest_V_reg_270;
reg   [25:0] trunc_ln_reg_275;
wire   [31:0] p_Result_s_fu_217_p5;
reg    ap_block_pp0_stage0_subdone;
wire    y_V_clip24_fu_155_ap_ready;
wire   [23:0] y_V_clip24_fu_155_ap_return;
reg    ap_block_pp0_stage0_01001;
wire  signed [23:0] s_V_fu_188_p1;
wire  signed [15:0] G_V_fu_192_p3;
wire  signed [39:0] prod_V_fu_229_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 m_axis_V_data_V_1_state = 2'd0;
#0 m_axis_V_keep_V_1_state = 2'd0;
#0 m_axis_V_strb_V_1_state = 2'd0;
#0 m_axis_V_user_V_1_state = 2'd0;
#0 m_axis_V_last_V_1_state = 2'd0;
#0 m_axis_V_id_V_1_state = 2'd0;
#0 m_axis_V_dest_V_1_state = 2'd0;
#0 m_axis_V_data_V_1_sel_rd = 1'b0;
#0 m_axis_V_data_V_1_sel_wr = 1'b0;
#0 m_axis_V_keep_V_1_sel_rd = 1'b0;
#0 m_axis_V_keep_V_1_sel_wr = 1'b0;
#0 m_axis_V_strb_V_1_sel_rd = 1'b0;
#0 m_axis_V_strb_V_1_sel_wr = 1'b0;
#0 m_axis_V_user_V_1_sel_rd = 1'b0;
#0 m_axis_V_user_V_1_sel_wr = 1'b0;
#0 m_axis_V_last_V_1_sel_rd = 1'b0;
#0 m_axis_V_last_V_1_sel_wr = 1'b0;
#0 m_axis_V_id_V_1_sel_rd = 1'b0;
#0 m_axis_V_id_V_1_sel_wr = 1'b0;
#0 m_axis_V_dest_V_1_sel_rd = 1'b0;
#0 m_axis_V_dest_V_1_sel_wr = 1'b0;
end

fx_gain_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
fx_gain_CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .gain_q2_14_V(gain_q2_14_V),
    .use_reg_V(use_reg_V)
);

clip24 y_V_clip24_fu_155(
    .ap_ready(y_V_clip24_fu_155_ap_ready),
    .v_V(trunc_ln_reg_275),
    .ap_return(y_V_clip24_fu_155_ap_return)
);

fx_gain_mul_mul_16s_24s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 40 ))
fx_gain_mul_mul_16s_24s_40_1_1_U2(
    .din0(G_V_fu_192_p3),
    .din1(s_V_fu_188_p1),
    .dout(prod_V_fu_229_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((m_axis_V_data_V_1_ack_out == 1'b1) & (m_axis_V_data_V_1_vld_out == 1'b1))) begin
            m_axis_V_data_V_1_sel_rd <= ~m_axis_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((m_axis_V_data_V_1_ack_in == 1'b1) & (m_axis_V_data_V_1_vld_in == 1'b1))) begin
            m_axis_V_data_V_1_sel_wr <= ~m_axis_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((m_axis_V_data_V_1_state == 2'd3) & (m_axis_V_data_V_1_vld_in == 1'b0) & (m_axis_V_data_V_1_ack_out == 1'b1)) | ((m_axis_V_data_V_1_state == 2'd2) & (m_axis_V_data_V_1_vld_in == 1'b0)))) begin
            m_axis_V_data_V_1_state <= 2'd2;
        end else if ((((m_axis_V_data_V_1_state == 2'd1) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_data_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0) & (m_axis_V_data_V_1_vld_in == 1'b1)))) begin
            m_axis_V_data_V_1_state <= 2'd1;
        end else if ((((m_axis_V_data_V_1_state == 2'd1) & (m_axis_V_data_V_1_ack_out == 1'b1)) | (~((m_axis_V_data_V_1_vld_in == 1'b0) & (m_axis_V_data_V_1_ack_out == 1'b1)) & ~((m_axis_TREADY == 1'b0) & (m_axis_V_data_V_1_vld_in == 1'b1)) & (m_axis_V_data_V_1_state == 2'd3)) | ((m_axis_V_data_V_1_state == 2'd2) & (m_axis_V_data_V_1_vld_in == 1'b1)))) begin
            m_axis_V_data_V_1_state <= 2'd3;
        end else begin
            m_axis_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((m_axis_V_dest_V_1_vld_out == 1'b1) & (m_axis_V_dest_V_1_ack_out == 1'b1))) begin
            m_axis_V_dest_V_1_sel_rd <= ~m_axis_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_dest_V_1_sel_wr <= 1'b0;
    end else begin
        if (((m_axis_V_dest_V_1_ack_in == 1'b1) & (m_axis_V_dest_V_1_vld_in == 1'b1))) begin
            m_axis_V_dest_V_1_sel_wr <= ~m_axis_V_dest_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((m_axis_V_dest_V_1_state == 2'd3) & (m_axis_V_dest_V_1_vld_in == 1'b0) & (m_axis_V_dest_V_1_ack_out == 1'b1)) | ((m_axis_V_dest_V_1_state == 2'd2) & (m_axis_V_dest_V_1_vld_in == 1'b0)))) begin
            m_axis_V_dest_V_1_state <= 2'd2;
        end else if ((((m_axis_V_dest_V_1_state == 2'd1) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_dest_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0) & (m_axis_V_dest_V_1_vld_in == 1'b1)))) begin
            m_axis_V_dest_V_1_state <= 2'd1;
        end else if ((((m_axis_V_dest_V_1_state == 2'd1) & (m_axis_V_dest_V_1_ack_out == 1'b1)) | (~((m_axis_V_dest_V_1_vld_in == 1'b0) & (m_axis_V_dest_V_1_ack_out == 1'b1)) & ~((m_axis_TREADY == 1'b0) & (m_axis_V_dest_V_1_vld_in == 1'b1)) & (m_axis_V_dest_V_1_state == 2'd3)) | ((m_axis_V_dest_V_1_state == 2'd2) & (m_axis_V_dest_V_1_vld_in == 1'b1)))) begin
            m_axis_V_dest_V_1_state <= 2'd3;
        end else begin
            m_axis_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((m_axis_V_id_V_1_vld_out == 1'b1) & (m_axis_V_id_V_1_ack_out == 1'b1))) begin
            m_axis_V_id_V_1_sel_rd <= ~m_axis_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_id_V_1_sel_wr <= 1'b0;
    end else begin
        if (((m_axis_V_id_V_1_ack_in == 1'b1) & (m_axis_V_id_V_1_vld_in == 1'b1))) begin
            m_axis_V_id_V_1_sel_wr <= ~m_axis_V_id_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((m_axis_V_id_V_1_state == 2'd3) & (m_axis_V_id_V_1_vld_in == 1'b0) & (m_axis_V_id_V_1_ack_out == 1'b1)) | ((m_axis_V_id_V_1_state == 2'd2) & (m_axis_V_id_V_1_vld_in == 1'b0)))) begin
            m_axis_V_id_V_1_state <= 2'd2;
        end else if ((((m_axis_V_id_V_1_state == 2'd1) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_id_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0) & (m_axis_V_id_V_1_vld_in == 1'b1)))) begin
            m_axis_V_id_V_1_state <= 2'd1;
        end else if ((((m_axis_V_id_V_1_state == 2'd1) & (m_axis_V_id_V_1_ack_out == 1'b1)) | (~((m_axis_V_id_V_1_vld_in == 1'b0) & (m_axis_V_id_V_1_ack_out == 1'b1)) & ~((m_axis_TREADY == 1'b0) & (m_axis_V_id_V_1_vld_in == 1'b1)) & (m_axis_V_id_V_1_state == 2'd3)) | ((m_axis_V_id_V_1_state == 2'd2) & (m_axis_V_id_V_1_vld_in == 1'b1)))) begin
            m_axis_V_id_V_1_state <= 2'd3;
        end else begin
            m_axis_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((m_axis_V_keep_V_1_ack_out == 1'b1) & (m_axis_V_keep_V_1_vld_out == 1'b1))) begin
            m_axis_V_keep_V_1_sel_rd <= ~m_axis_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_keep_V_1_sel_wr <= 1'b0;
    end else begin
        if (((m_axis_V_keep_V_1_ack_in == 1'b1) & (m_axis_V_keep_V_1_vld_in == 1'b1))) begin
            m_axis_V_keep_V_1_sel_wr <= ~m_axis_V_keep_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((m_axis_V_keep_V_1_state == 2'd3) & (m_axis_V_keep_V_1_vld_in == 1'b0) & (m_axis_V_keep_V_1_ack_out == 1'b1)) | ((m_axis_V_keep_V_1_state == 2'd2) & (m_axis_V_keep_V_1_vld_in == 1'b0)))) begin
            m_axis_V_keep_V_1_state <= 2'd2;
        end else if ((((m_axis_V_keep_V_1_state == 2'd1) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_keep_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0) & (m_axis_V_keep_V_1_vld_in == 1'b1)))) begin
            m_axis_V_keep_V_1_state <= 2'd1;
        end else if ((((m_axis_V_keep_V_1_state == 2'd1) & (m_axis_V_keep_V_1_ack_out == 1'b1)) | (~((m_axis_V_keep_V_1_vld_in == 1'b0) & (m_axis_V_keep_V_1_ack_out == 1'b1)) & ~((m_axis_TREADY == 1'b0) & (m_axis_V_keep_V_1_vld_in == 1'b1)) & (m_axis_V_keep_V_1_state == 2'd3)) | ((m_axis_V_keep_V_1_state == 2'd2) & (m_axis_V_keep_V_1_vld_in == 1'b1)))) begin
            m_axis_V_keep_V_1_state <= 2'd3;
        end else begin
            m_axis_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((m_axis_V_last_V_1_vld_out == 1'b1) & (m_axis_V_last_V_1_ack_out == 1'b1))) begin
            m_axis_V_last_V_1_sel_rd <= ~m_axis_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((m_axis_V_last_V_1_ack_in == 1'b1) & (m_axis_V_last_V_1_vld_in == 1'b1))) begin
            m_axis_V_last_V_1_sel_wr <= ~m_axis_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((m_axis_V_last_V_1_state == 2'd3) & (m_axis_V_last_V_1_vld_in == 1'b0) & (m_axis_V_last_V_1_ack_out == 1'b1)) | ((m_axis_V_last_V_1_state == 2'd2) & (m_axis_V_last_V_1_vld_in == 1'b0)))) begin
            m_axis_V_last_V_1_state <= 2'd2;
        end else if ((((m_axis_V_last_V_1_state == 2'd1) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_last_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0) & (m_axis_V_last_V_1_vld_in == 1'b1)))) begin
            m_axis_V_last_V_1_state <= 2'd1;
        end else if ((((m_axis_V_last_V_1_state == 2'd1) & (m_axis_V_last_V_1_ack_out == 1'b1)) | (~((m_axis_V_last_V_1_vld_in == 1'b0) & (m_axis_V_last_V_1_ack_out == 1'b1)) & ~((m_axis_TREADY == 1'b0) & (m_axis_V_last_V_1_vld_in == 1'b1)) & (m_axis_V_last_V_1_state == 2'd3)) | ((m_axis_V_last_V_1_state == 2'd2) & (m_axis_V_last_V_1_vld_in == 1'b1)))) begin
            m_axis_V_last_V_1_state <= 2'd3;
        end else begin
            m_axis_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((m_axis_V_strb_V_1_ack_out == 1'b1) & (m_axis_V_strb_V_1_vld_out == 1'b1))) begin
            m_axis_V_strb_V_1_sel_rd <= ~m_axis_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_strb_V_1_sel_wr <= 1'b0;
    end else begin
        if (((m_axis_V_strb_V_1_ack_in == 1'b1) & (m_axis_V_strb_V_1_vld_in == 1'b1))) begin
            m_axis_V_strb_V_1_sel_wr <= ~m_axis_V_strb_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((m_axis_V_strb_V_1_state == 2'd3) & (m_axis_V_strb_V_1_vld_in == 1'b0) & (m_axis_V_strb_V_1_ack_out == 1'b1)) | ((m_axis_V_strb_V_1_state == 2'd2) & (m_axis_V_strb_V_1_vld_in == 1'b0)))) begin
            m_axis_V_strb_V_1_state <= 2'd2;
        end else if ((((m_axis_V_strb_V_1_state == 2'd1) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_strb_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0) & (m_axis_V_strb_V_1_vld_in == 1'b1)))) begin
            m_axis_V_strb_V_1_state <= 2'd1;
        end else if ((((m_axis_V_strb_V_1_state == 2'd1) & (m_axis_V_strb_V_1_ack_out == 1'b1)) | (~((m_axis_V_strb_V_1_vld_in == 1'b0) & (m_axis_V_strb_V_1_ack_out == 1'b1)) & ~((m_axis_TREADY == 1'b0) & (m_axis_V_strb_V_1_vld_in == 1'b1)) & (m_axis_V_strb_V_1_state == 2'd3)) | ((m_axis_V_strb_V_1_state == 2'd2) & (m_axis_V_strb_V_1_vld_in == 1'b1)))) begin
            m_axis_V_strb_V_1_state <= 2'd3;
        end else begin
            m_axis_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((m_axis_V_user_V_1_ack_out == 1'b1) & (m_axis_V_user_V_1_vld_out == 1'b1))) begin
            m_axis_V_user_V_1_sel_rd <= ~m_axis_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((m_axis_V_user_V_1_ack_in == 1'b1) & (m_axis_V_user_V_1_vld_in == 1'b1))) begin
            m_axis_V_user_V_1_sel_wr <= ~m_axis_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((m_axis_V_user_V_1_state == 2'd3) & (m_axis_V_user_V_1_vld_in == 1'b0) & (m_axis_V_user_V_1_ack_out == 1'b1)) | ((m_axis_V_user_V_1_state == 2'd2) & (m_axis_V_user_V_1_vld_in == 1'b0)))) begin
            m_axis_V_user_V_1_state <= 2'd2;
        end else if ((((m_axis_V_user_V_1_state == 2'd1) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_user_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0) & (m_axis_V_user_V_1_vld_in == 1'b1)))) begin
            m_axis_V_user_V_1_state <= 2'd1;
        end else if ((((m_axis_V_user_V_1_state == 2'd1) & (m_axis_V_user_V_1_ack_out == 1'b1)) | (~((m_axis_V_user_V_1_vld_in == 1'b0) & (m_axis_V_user_V_1_ack_out == 1'b1)) & ~((m_axis_TREADY == 1'b0) & (m_axis_V_user_V_1_vld_in == 1'b1)) & (m_axis_V_user_V_1_state == 2'd3)) | ((m_axis_V_user_V_1_state == 2'd2) & (m_axis_V_user_V_1_vld_in == 1'b1)))) begin
            m_axis_V_user_V_1_state <= 2'd3;
        end else begin
            m_axis_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_data_V_1_load_A == 1'b1)) begin
        m_axis_V_data_V_1_payload_A <= p_Result_s_fu_217_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_data_V_1_load_B == 1'b1)) begin
        m_axis_V_data_V_1_payload_B <= p_Result_s_fu_217_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_dest_V_1_load_A == 1'b1)) begin
        m_axis_V_dest_V_1_payload_A <= tmp_dest_V_reg_270;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_dest_V_1_load_B == 1'b1)) begin
        m_axis_V_dest_V_1_payload_B <= tmp_dest_V_reg_270;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_id_V_1_load_A == 1'b1)) begin
        m_axis_V_id_V_1_payload_A <= tmp_id_V_reg_265;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_id_V_1_load_B == 1'b1)) begin
        m_axis_V_id_V_1_payload_B <= tmp_id_V_reg_265;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_keep_V_1_load_A == 1'b1)) begin
        m_axis_V_keep_V_1_payload_A <= tmp_keep_V_reg_245;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_keep_V_1_load_B == 1'b1)) begin
        m_axis_V_keep_V_1_payload_B <= tmp_keep_V_reg_245;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_last_V_1_load_A == 1'b1)) begin
        m_axis_V_last_V_1_payload_A <= tmp_last_V_reg_260;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_last_V_1_load_B == 1'b1)) begin
        m_axis_V_last_V_1_payload_B <= tmp_last_V_reg_260;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_strb_V_1_load_A == 1'b1)) begin
        m_axis_V_strb_V_1_payload_A <= tmp_strb_V_reg_250;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_strb_V_1_load_B == 1'b1)) begin
        m_axis_V_strb_V_1_payload_B <= tmp_strb_V_reg_250;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_user_V_1_load_A == 1'b1)) begin
        m_axis_V_user_V_1_payload_A <= tmp_user_V_reg_255;
    end
end

always @ (posedge ap_clk) begin
    if ((m_axis_V_user_V_1_load_B == 1'b1)) begin
        m_axis_V_user_V_1_payload_B <= tmp_user_V_reg_255;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_92_p9 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_V_1_reg_240 <= s_axis_TDATA;
        tmp_dest_V_reg_270 <= s_axis_TDEST;
        tmp_id_V_reg_265 <= s_axis_TID;
        tmp_keep_V_reg_245 <= s_axis_TKEEP;
        tmp_last_V_reg_260 <= s_axis_TLAST;
        tmp_strb_V_reg_250 <= s_axis_TSTRB;
        tmp_user_V_reg_255 <= s_axis_TUSER;
        trunc_ln_reg_275 <= {{prod_V_fu_229_p2[39:14]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_236 <= tmp_nbreadreq_fu_92_p9;
        tmp_reg_236_pp0_iter1_reg <= tmp_reg_236;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (tmp_reg_236_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        m_axis_TDATA_blk_n = m_axis_V_data_V_1_state[1'd1];
    end else begin
        m_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((m_axis_V_data_V_1_sel == 1'b1)) begin
        m_axis_V_data_V_1_data_out = m_axis_V_data_V_1_payload_B;
    end else begin
        m_axis_V_data_V_1_data_out = m_axis_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_V_data_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_V_dest_V_1_sel == 1'b1)) begin
        m_axis_V_dest_V_1_data_out = m_axis_V_dest_V_1_payload_B;
    end else begin
        m_axis_V_dest_V_1_data_out = m_axis_V_dest_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_V_dest_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_V_id_V_1_sel == 1'b1)) begin
        m_axis_V_id_V_1_data_out = m_axis_V_id_V_1_payload_B;
    end else begin
        m_axis_V_id_V_1_data_out = m_axis_V_id_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_V_id_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_V_keep_V_1_sel == 1'b1)) begin
        m_axis_V_keep_V_1_data_out = m_axis_V_keep_V_1_payload_B;
    end else begin
        m_axis_V_keep_V_1_data_out = m_axis_V_keep_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_V_keep_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_V_last_V_1_sel == 1'b1)) begin
        m_axis_V_last_V_1_data_out = m_axis_V_last_V_1_payload_B;
    end else begin
        m_axis_V_last_V_1_data_out = m_axis_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_V_last_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_V_strb_V_1_sel == 1'b1)) begin
        m_axis_V_strb_V_1_data_out = m_axis_V_strb_V_1_payload_B;
    end else begin
        m_axis_V_strb_V_1_data_out = m_axis_V_strb_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_V_strb_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_V_user_V_1_sel == 1'b1)) begin
        m_axis_V_user_V_1_data_out = m_axis_V_user_V_1_payload_B;
    end else begin
        m_axis_V_user_V_1_data_out = m_axis_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_236 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_V_user_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (tmp_nbreadreq_fu_92_p9 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_92_p9 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        s_axis_TREADY = 1'b1;
    end else begin
        s_axis_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign G_V_fu_192_p3 = ((use_reg_V[0:0] === 1'b1) ? gain_q2_14_V : 16'd23170);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_start == 1'b1) & ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_92_p9 == 1'd1) & (s_axis_TVALID == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((m_axis_V_user_V_1_state == 2'd1) | (m_axis_V_strb_V_1_state == 2'd1) | (m_axis_V_keep_V_1_state == 2'd1) | (m_axis_V_dest_V_1_state == 2'd1) | (m_axis_V_id_V_1_state == 2'd1) | (m_axis_V_last_V_1_state == 2'd1) | (m_axis_V_data_V_1_state == 2'd1) | ((m_axis_V_user_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_strb_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_keep_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_data_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_dest_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_id_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_last_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_92_p9 == 1'd1) & (s_axis_TVALID == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((m_axis_V_user_V_1_state == 2'd1) | (m_axis_V_strb_V_1_state == 2'd1) | (m_axis_V_keep_V_1_state == 2'd1) | (m_axis_V_dest_V_1_state == 2'd1) | (m_axis_V_id_V_1_state == 2'd1) | (m_axis_V_last_V_1_state == 2'd1) | (m_axis_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state3_io) | ((m_axis_V_user_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_strb_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_keep_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_data_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_dest_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_id_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_last_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_92_p9 == 1'd1) & (s_axis_TVALID == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((m_axis_V_user_V_1_state == 2'd1) | (m_axis_V_strb_V_1_state == 2'd1) | (m_axis_V_keep_V_1_state == 2'd1) | (m_axis_V_dest_V_1_state == 2'd1) | (m_axis_V_id_V_1_state == 2'd1) | (m_axis_V_last_V_1_state == 2'd1) | (m_axis_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state3_io) | ((m_axis_V_user_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_strb_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_keep_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_data_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_dest_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_id_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_last_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_92_p9 == 1'd1) & (s_axis_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((tmp_reg_236 == 1'd1) & (m_axis_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((tmp_reg_236_pp0_iter1_reg == 1'd1) & (m_axis_V_data_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((m_axis_V_user_V_1_state == 2'd1) | (m_axis_V_strb_V_1_state == 2'd1) | (m_axis_V_keep_V_1_state == 2'd1) | (m_axis_V_dest_V_1_state == 2'd1) | (m_axis_V_id_V_1_state == 2'd1) | (m_axis_V_last_V_1_state == 2'd1) | (m_axis_V_data_V_1_state == 2'd1) | ((m_axis_V_user_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_strb_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_keep_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_data_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_dest_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_id_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)) | ((m_axis_V_last_V_1_state == 2'd3) & (m_axis_TREADY == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign m_axis_TDATA = m_axis_V_data_V_1_data_out;

assign m_axis_TDEST = m_axis_V_dest_V_1_data_out;

assign m_axis_TID = m_axis_V_id_V_1_data_out;

assign m_axis_TKEEP = m_axis_V_keep_V_1_data_out;

assign m_axis_TLAST = m_axis_V_last_V_1_data_out;

assign m_axis_TSTRB = m_axis_V_strb_V_1_data_out;

assign m_axis_TUSER = m_axis_V_user_V_1_data_out;

assign m_axis_TVALID = m_axis_V_dest_V_1_state[1'd0];

assign m_axis_V_data_V_1_ack_in = m_axis_V_data_V_1_state[1'd1];

assign m_axis_V_data_V_1_ack_out = m_axis_TREADY;

assign m_axis_V_data_V_1_load_A = (m_axis_V_data_V_1_state_cmp_full & ~m_axis_V_data_V_1_sel_wr);

assign m_axis_V_data_V_1_load_B = (m_axis_V_data_V_1_state_cmp_full & m_axis_V_data_V_1_sel_wr);

assign m_axis_V_data_V_1_sel = m_axis_V_data_V_1_sel_rd;

assign m_axis_V_data_V_1_state_cmp_full = ((m_axis_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_data_V_1_vld_out = m_axis_V_data_V_1_state[1'd0];

assign m_axis_V_dest_V_1_ack_in = m_axis_V_dest_V_1_state[1'd1];

assign m_axis_V_dest_V_1_ack_out = m_axis_TREADY;

assign m_axis_V_dest_V_1_load_A = (m_axis_V_dest_V_1_state_cmp_full & ~m_axis_V_dest_V_1_sel_wr);

assign m_axis_V_dest_V_1_load_B = (m_axis_V_dest_V_1_state_cmp_full & m_axis_V_dest_V_1_sel_wr);

assign m_axis_V_dest_V_1_sel = m_axis_V_dest_V_1_sel_rd;

assign m_axis_V_dest_V_1_state_cmp_full = ((m_axis_V_dest_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_dest_V_1_vld_out = m_axis_V_dest_V_1_state[1'd0];

assign m_axis_V_id_V_1_ack_in = m_axis_V_id_V_1_state[1'd1];

assign m_axis_V_id_V_1_ack_out = m_axis_TREADY;

assign m_axis_V_id_V_1_load_A = (m_axis_V_id_V_1_state_cmp_full & ~m_axis_V_id_V_1_sel_wr);

assign m_axis_V_id_V_1_load_B = (m_axis_V_id_V_1_state_cmp_full & m_axis_V_id_V_1_sel_wr);

assign m_axis_V_id_V_1_sel = m_axis_V_id_V_1_sel_rd;

assign m_axis_V_id_V_1_state_cmp_full = ((m_axis_V_id_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_id_V_1_vld_out = m_axis_V_id_V_1_state[1'd0];

assign m_axis_V_keep_V_1_ack_in = m_axis_V_keep_V_1_state[1'd1];

assign m_axis_V_keep_V_1_ack_out = m_axis_TREADY;

assign m_axis_V_keep_V_1_load_A = (m_axis_V_keep_V_1_state_cmp_full & ~m_axis_V_keep_V_1_sel_wr);

assign m_axis_V_keep_V_1_load_B = (m_axis_V_keep_V_1_state_cmp_full & m_axis_V_keep_V_1_sel_wr);

assign m_axis_V_keep_V_1_sel = m_axis_V_keep_V_1_sel_rd;

assign m_axis_V_keep_V_1_state_cmp_full = ((m_axis_V_keep_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_keep_V_1_vld_out = m_axis_V_keep_V_1_state[1'd0];

assign m_axis_V_last_V_1_ack_in = m_axis_V_last_V_1_state[1'd1];

assign m_axis_V_last_V_1_ack_out = m_axis_TREADY;

assign m_axis_V_last_V_1_load_A = (m_axis_V_last_V_1_state_cmp_full & ~m_axis_V_last_V_1_sel_wr);

assign m_axis_V_last_V_1_load_B = (m_axis_V_last_V_1_state_cmp_full & m_axis_V_last_V_1_sel_wr);

assign m_axis_V_last_V_1_sel = m_axis_V_last_V_1_sel_rd;

assign m_axis_V_last_V_1_state_cmp_full = ((m_axis_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_last_V_1_vld_out = m_axis_V_last_V_1_state[1'd0];

assign m_axis_V_strb_V_1_ack_in = m_axis_V_strb_V_1_state[1'd1];

assign m_axis_V_strb_V_1_ack_out = m_axis_TREADY;

assign m_axis_V_strb_V_1_load_A = (m_axis_V_strb_V_1_state_cmp_full & ~m_axis_V_strb_V_1_sel_wr);

assign m_axis_V_strb_V_1_load_B = (m_axis_V_strb_V_1_state_cmp_full & m_axis_V_strb_V_1_sel_wr);

assign m_axis_V_strb_V_1_sel = m_axis_V_strb_V_1_sel_rd;

assign m_axis_V_strb_V_1_state_cmp_full = ((m_axis_V_strb_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_strb_V_1_vld_out = m_axis_V_strb_V_1_state[1'd0];

assign m_axis_V_user_V_1_ack_in = m_axis_V_user_V_1_state[1'd1];

assign m_axis_V_user_V_1_ack_out = m_axis_TREADY;

assign m_axis_V_user_V_1_load_A = (m_axis_V_user_V_1_state_cmp_full & ~m_axis_V_user_V_1_sel_wr);

assign m_axis_V_user_V_1_load_B = (m_axis_V_user_V_1_state_cmp_full & m_axis_V_user_V_1_sel_wr);

assign m_axis_V_user_V_1_sel = m_axis_V_user_V_1_sel_rd;

assign m_axis_V_user_V_1_state_cmp_full = ((m_axis_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_user_V_1_vld_out = m_axis_V_user_V_1_state[1'd0];

assign p_Result_s_fu_217_p5 = {{tmp_data_V_1_reg_240[31:24]}, {y_V_clip24_fu_155_ap_return}};

assign s_V_fu_188_p1 = s_axis_TDATA[23:0];

assign tmp_nbreadreq_fu_92_p9 = s_axis_TVALID;

endmodule //fx_gain
