#!/usr/bin/env python3
"""Deployed-bitstream baseline registry (Tier 4).

Single source of truth for "which bit/hwh is which decision". The md5s are
NEVER stored -- they are computed live from git (`git show <commit>:<path>`),
so they cannot drift or be copy-pasted wrong (the bug that once recorded the
D99 hwh as D98's `8f7bb979`). Edit the seed in docs/ai_context/baselines.json
(decision / commit / status / note only). The `current_deployed` seed name is
historical; in practice it marks the current accepted committed baseline, not
an uncommitted live-board candidate.

Commands:
  python3 tools/baselines.py current   # md5 the working-tree bit/hwh, name the matching baseline
  python3 tools/baselines.py render    # (re)generate docs/ai_context/BASELINES.md
  python3 tools/baselines.py verify     # check commits resolve + deployed md5 matches the working tree
"""
import hashlib
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON = os.path.join(REPO, "docs", "ai_context", "baselines.json")
MD = os.path.join(REPO, "docs", "ai_context", "BASELINES.md")
EMPTY_MD5 = hashlib.md5(b"").hexdigest()


def _load():
    with open(JSON) as f:
        return json.load(f)


def md5_at(commit, path):
    """md5 of <path> at <commit> in git, or None if it is not there."""
    try:
        out = subprocess.run(["git", "show", "%s:%s" % (commit, path)],
                             cwd=REPO, stdout=subprocess.PIPE,
                             stderr=subprocess.DEVNULL)
    except Exception:
        return None
    if out.returncode != 0 or not out.stdout:
        return None
    h = hashlib.md5(out.stdout).hexdigest()
    return None if h == EMPTY_MD5 else h


def md5_file(path):
    p = os.path.join(REPO, path)
    if not os.path.exists(p):
        return None
    with open(p, "rb") as f:
        return hashlib.md5(f.read()).hexdigest()


def _rows(cfg):
    for b in cfg["baselines"]:
        if b["status"].endswith("sourceonly"):
            # e.g. D120: only the source was committed, never a rebuilt bit, so
            # the bit at that commit is an inherited stale one -- do not show it.
            yield b, None, None
        else:
            yield b, md5_at(b["commit"], cfg["bit_path"]), md5_at(b["commit"], cfg["hwh_path"])


def cmd_render(cfg):
    cur = cfg.get("current_deployed")
    lines = [
        "# Deployed bitstream baselines",
        "",
        "**Generated by `tools/baselines.py render` -- do not hand-edit.** The",
        "md5s are computed live from git, so they cannot drift. Edit the seed in",
        "`baselines.json` and re-run. `>>` marks the current accepted committed baseline.",
        "",
        "| | Decision | Status | Commit | bit md5 | hwh md5 | Date | Note |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for b, bm, hm in _rows(cfg):
        mark = ">>" if b["commit"] == cur else ""
        lines.append("| {} | {} | {} | `{}` | `{}` | `{}` | {} | {} |".format(
            mark, b["decision"], b["status"], b["commit"],
            (bm or "(source only)"), (hm or "(source only)"),
            b.get("date", ""), b.get("note", "").replace("|", "\\|")))
    lines.append("")
    with open(MD, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d baselines)" % (MD, len(cfg["baselines"])))


def cmd_current(cfg):
    wb, wh = md5_file(cfg["bit_path"]), md5_file(cfg["hwh_path"])
    print("working tree: bit %s | hwh %s" % (wb, wh))
    match = [b["decision"] for b, bm, _ in _rows(cfg) if bm and bm == wb]
    print("matches baseline(s): %s" % (", ".join(match) if match else "NONE"))
    cur = cfg.get("current_deployed")
    cm = md5_at(cur, cfg["bit_path"])
    ok = (cm == wb)
    print("current_deployed = %s (bit %s) -- working tree %s" %
          (cur, cm, "MATCHES" if ok else "DIFFERS (uncommitted DSP change?)"))
    return 0 if ok else 1


def cmd_verify(cfg):
    rc = 0
    seen = {}
    for b, bm, hm in _rows(cfg):
        if bm is None and not b["status"].endswith("sourceonly"):
            print("FAIL %-14s commit %s: bit not found in git" % (b["decision"], b["commit"]))
            rc = 1
        if bm:
            seen.setdefault(bm, []).append(b["decision"])
    for h, decs in seen.items():
        if len(decs) > 1:
            print("note: identical bit md5 %s shared by %s" % (h[:12], ", ".join(decs)))
    wb = md5_file(cfg["bit_path"])
    cm = md5_at(cfg["current_deployed"], cfg["bit_path"])
    if wb != cm:
        print("FAIL current_deployed %s bit (%s) != working tree (%s)" %
              (cfg["current_deployed"], cm, wb))
        rc = 1
    print("verify: %s" % ("OK" if rc == 0 else "PROBLEMS"))
    return rc


def main():
    cfg = _load()
    cmd = sys.argv[1] if len(sys.argv) > 1 else "current"
    if cmd == "render":
        cmd_render(cfg)
    elif cmd == "verify":
        sys.exit(cmd_verify(cfg))
    elif cmd == "current":
        sys.exit(cmd_current(cfg))
    else:
        print(__doc__)
        sys.exit(2)


if __name__ == "__main__":
    main()
